### ISSUE TITLE
Vagrant Up fails

### ISSUE THREAD

**Issue by barmstrong** [reddit/reddit-vagrant#26]
Trying to get vagrant up working, here are the last few lines where it fails:

```
==> default: And if you think caching might be hurting you, you can flush memcache with
==> default: 
==> default:     reddit-flush
==> default: 
==> default: Now that the core of reddit is installed, you may want to do some additional
==> default: steps:
==> default: 
==> default: * Ensure that reddit.local resolves to this machine.
==> default: 
==> default: * To populate the database with test data, run:
==> default: 
==> default:     cd /host/src/reddit
==> default:     reddit-run scripts/inject_test_data.py -c 'inject_test_data()'
==> default: 
==> default: * Manually run reddit-job-update_reddits immediately after populating the db
==> default:   or adding your own subreddits.
==> default: + '[' 1 ']'
==> default: + /sbin/initctl emit reddit-stop
==> default: + eval 'cd /host/src/reddit; /usr/local/bin/reddit-run scripts/inject_test_data.py -c '\''inject_test_data()'\'''
==> default: ++ cd /host/src/reddit
==> default: ++ /usr/local/bin/reddit-run scripts/inject_test_data.py -c 'inject_test_data()'
==> default: Warning: g.media_domain == g.domain. This may give untrusted content access to user cookies
==> default: Warning: g.oauth_domain == g.domain. CORS requests to g.domain will be allowed
==> default: Overriding g.--plugin to r2
==> default: reddit:15236 started 8463225 at 01:27:54 (took 0.51s)
==> default: /tmp/vagrant-shell: line 31: 15236 Killed                  /usr/local/bin/reddit-run scripts/inject_test_data.py -c 'inject_test_data()'
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

Using VirtualBox 5.0.8 on OS X. Any ideas?

**Comment by barmstrong** [comment]
If I do `vagrant ssh` and try to re-run the last command I get this:

```
vagrant@reddit:/host/src/reddit$ reddit-run scripts/inject_test_data.py -c 'inject_test_data()'
Warning: g.media_domain == g.domain. This may give untrusted content access to user cookies
Warning: g.oauth_domain == g.domain. CORS requests to g.domain will be allowed
Overriding g.--plugin to r2
Traceback (most recent call last):
  File "/usr/bin/paster", line 4, in <module>
    command.run()
  File "/usr/lib/python2.7/dist-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/python2.7/dist-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/python2.7/dist-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/host/src/reddit/r2/r2/commands.py", line 68, in command
    config_name, relative_to=here_dir, global_conf=global_conf)
  File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/lib/python2.7/dist-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/host/src/reddit/r2/r2/__init__.py", line 41, in make_app
    return real_make_app(*args, **kwargs)
  File "/host/src/reddit/r2/r2/config/middleware.py", line 516, in make_app
    config = load_environment(global_conf, app_conf)
  File "/host/src/reddit/r2/r2/config/environment.py", line 75, in load_environment
    g.setup()
  File "/host/src/reddit/r2/r2/lib/app_globals.py", line 788, in setup
    self.cassandra_pools[self.cassandra_default_pool],
  File "/host/src/reddit/r2/r2/lib/cache.py", line 923, in _setup_column_family
    write_consistency_level=CL_QUORUM)
  File "/usr/lib/python2.7/dist-packages/pycassa/columnfamily.py", line 284, in __init__
    self.load_schema()
  File "/usr/lib/python2.7/dist-packages/pycassa/columnfamily.py", line 306, in load_schema
    use_dict_for_col_metadata=True)
  File "/usr/lib/python2.7/dist-packages/pycassa/pool.py", line 576, in execute
    conn = self.get()
  File "/usr/lib/python2.7/dist-packages/pycassa/pool.py", line 539, in get
    conn = self._new_if_required(self._pool_size)
  File "/usr/lib/python2.7/dist-packages/pycassa/pool.py", line 520, in _new_if_required
    return self._create_connection()
  File "/usr/lib/python2.7/dist-packages/pycassa/pool.py", line 431, in _create_connection
    (exc.__class__.__name__, exc))
pycassa.pool.AllServersUnavailable: An attempt was made to connect to each of the servers twice, but none of the attempts succeeded. The last failure was TTransportException: Could not connect to 127.0.0.1:9160
vagrant@reddit:/host/src/reddit$
```

**Comment by kjoconnor** [comment]
Looks like your Cassandra installation is either not running or was never installed correctly. Can you try `/etc/init.d/cassandra status` and check logs in `/var/log/cassandra`?

**Comment by barmstrong** [comment]
Hmm...

```
vagrant@reddit:/host/src/reddit$ sudo /etc/init.d/cassandra status
 * could not access pidfile for Cassandra
vagrant@reddit:/host/src/reddit$ cat /var/log/cassandra
cat: /var/log/cassandra: Is a directory
vagrant@reddit:/host/src/reddit$
```

Maybe it never installed. Let me grab the full logs

**Comment by kjoconnor** [comment]
If you can open a thread over on https://www.reddit.com/r/redditdev that'd be great. We're going to try and keep this issue tracker for confirmed bugs only.

Thanks!

**Comment by barmstrong** [comment]
No prob, done: https://www.reddit.com/r/redditdev/comments/3r1d0j/vagrant_up_fails/ (with full logs)

Thanks!
